# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # linting
      - run: npm run lint

      # build

      - run: npm run build

  test:
    docker:
      - image: circleci/node:7.10-browsers

    working_directory: ~/repo

    steps:

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test

      - store_test_results:
          path: /tmp/test-results/unit

  ui-test:
    docker:
      - image: circleci/node:7.10-browsers
      
    working_directory: ~/repo

    steps:

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run ui-test

      - store_test_results:
          path: /tmp/test-results/ui

  deploy:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ee:35:2d:c3:39:34:c4:23:0a:fa:d6:51:ea:9d:11:5c"

      - attach_workspace:
          at: ~/repo

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: git config --global user.email $GH_EMAIL && git config --global user.name $GH_NAME

      - run: npm run deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - ui-test
      - deploy:
          requires:
            - build
            - test
            - ui-test
          filters:
            branches: 
              only:
                - master
